name: 'Build and test container'
description: 'Updates an ECR service to force a new deployment'
inputs:
  run-tests:
    description: "Should tests be run in docker before building and running"
    required: false
  application-name:
    description: "Name of the application/container" 
    required: true
  container-port:
    description: Port the container is exposing
    default: "3000"
    required: true 
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/script.sh
      id: main
      env:
         APPLICATION_NAME: ${{ inputs.application-name }}
         RUN_TESTS: ${{ inputs.run-tests }}
         PORT: ${{ inputs.container-port }}
      shell: bash