name: 'Build and test container'
description: 'Updates an ECR service to force a new deployment'
inputs:
  run-tests:
    description: "Should tests be run in docker before building and running"
    required: false
  application-name:
    description: "Name of the application/container" 
    required: true
  container-port:
    description: Port the container is exposing
    default: "3000"
    required: true 
  app-path:
    description: Directory the application lives in
    required: false
    default: .
  build-script:
    required: false
    type: string
  run-script:
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/script.sh
      id: main
      env:
          APPLICATION_NAME: ${{ inputs.application-name }}
          RUN_TESTS: ${{ inputs.run-tests }}
          PORT: ${{ inputs.container-port }}
          APP_PATH: ${{ inputs.app-path }}
          BUILD_SCRIPT: ${{ inputs.build-script }}
          RUN_SCRIPT: ${{ inputs.run-script }}
      shell: bash